import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TransactionProvider from "@/store/TransactionsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TransactionProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </TransactionProvider>
  );
}
